---

- hosts: all
  become: true
  tasks:
  
  - name: install the lastest version of httpd
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"
    
  - name: install the lastest version of Apache2
    yum:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

 
